package org.openmrs.contrib.qa;// Generated by Selenium IDE

import org.junit.Ignore;
import org.junit.Test;
import org.openmrs.contrib.qa.selenium.Browse;
import org.openmrs.contrib.qa.selenium.DriverProvider;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

//Original copy exported from selenium ide (extension) to java test from src/test/resources/openmrs.slide
@Ignore
public class MultipleBrowserLoginAndOutTest {

  @Test
  public void loginAndOut() {

    for(DriverProvider driverProvider : DriverProvider.values()) {
      WebDriver driver = Browse.driver(driverProvider);
      driver.get("https://demo.openmrs.org/openmrs/login.htm");
      driver.findElement(By.id("username")).sendKeys("admin");
      driver.findElement(By.id("password")).click();
      driver.findElement(By.id("password")).sendKeys("Admin123");
      driver.findElement(By.id("Pharmacy")).click();
      driver.findElement(By.id("loginButton")).click();
      driver.findElement(By.linkText("Logout")).click();
    }
  }
}
